model_id: spy_opt_intraday_hourly
ticker: SPY
asset_type: opt
horizon: intraday
cadence: hourly
indicator_set: momo_opt_default
model: gbm
task: classification
hyperparams:
  n_estimators: 300
  max_depth: 6
  learning_rate: 0.05
features:
  time:
    day_of_week: true
    hour_of_day: true
labels:
  kind: next_bar_updown
