model_id: spy_eq_swing_daily_breakout
ticker: SPY
asset_type: eq
horizon: swing
cadence: daily
indicator_set: swing_eq_breakout
model: gbm
task: classification
hyperparams:
  n_estimators: 300
  max_depth: 6
  learning_rate: 0.05
features:
  time:
    day_of_week: true
labels:
  kind: fwd_ret_20d
