# packs/zerosigma/policy_templates/default.yaml
name: zeroedge_default_v1
version: 1
description: "Default policy for 0DTE strategies"
risk:
  max_drawdown: 0.1
  max_exposure: 10000
execution:
  slippage_bps: 1.0
  size_by_conf: false
  conf_cap: 1.0
  momentum_gate: false
  momentum_min: 0.0
  momentum_column: momentum_score_total
alerting:
  cooldown_minutes: 5
  max_trades_per_day: 10
