name: CI

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx
      - name: Run core tests
        run: |
          pytest -q products/sigma-core/tests || (echo "core tests failed" && exit 1)
      - name: Run API tests
        env:
          # Ensure DB not required
          DB_USER: ""
        run: |
          pytest -q products/sigma-lab/api/tests || (echo "api tests failed" && exit 1)
