name: Lint (Sigma Core)

on:
  pull_request:
    paths:
      - 'products/sigma-core/**'
      - '.github/workflows/lint.yml'
  push:
    branches: [ main ]
    paths:
      - 'products/sigma-core/**'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run catalog lints
        run: make -C products/sigma-core lint-catalog

      - name: Run strategies lints
        run: make -C products/sigma-core lint-strategies

      - name: Run workflows lints
        run: make -C products/sigma-core lint-workflows

      - name: Run presets lints
        run: make -C products/sigma-core lint-presets

      - name: Run training config lints
        run: make -C products/sigma-core lint-training-cfg

